version: "3"
services:
  laravel:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: cube_php_laravel_laravel
    environment:
      - ELASTIC_APM_SERVICE_NAME=cube_sample_app_php_laravel_elastic
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:3130

      # optional settings
      # - ELASTIC_APM_ENVIRONMENT=UNSET
      # - ELASTIC_APM_SERVICE_VERSION=1.2.3
      # - ELASTIC_APM_GLOBAL_LABELS=mykey1=myvalue1,mykey2=myvalue2

      # Print Elastic agent logs on screen
      # - ELASTIC_APM_LOG_FILE=stdout
      # Set Elastic agent log level to debug if needed to see detailed logs
      # - ELASTIC_APM_LOG_LEVEL=debug
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    restart: always

  laravel_worker:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
    command: ["php", "artisan", "queue:work"]
    container_name: cube_php_laravel_laravel_worker
    environment:
      - ELASTIC_APM_SERVICE_NAME=cube_sample_app_php_laravel_elastic
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:3130

      # optional settings
      # - ELASTIC_APM_ENVIRONMENT=UNSET
      # - ELASTIC_APM_SERVICE_VERSION=1.2.3
      # - ELASTIC_APM_GLOBAL_LABELS=mykey1=myvalue1,mykey2=myvalue2

      # Print Elastic agent logs on screen
      # - ELASTIC_APM_LOG_FILE=stdout
      # Set Elastic agent log level to debug if needed to see detailed logs
      # - ELASTIC_APM_LOG_LEVEL=debug
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_php_laravel_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_php_laravel_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_php_laravel_redis

volumes:
  cube_php_laravel_mysql:
