version: "3"
services:
  laravel:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        # New Relic agent will send data on https://<domain_of_cubeapm_server>:443
        NEW_RELIC_HOST: <domain_of_cubeapm_server>
    container_name: cube_php_laravel_laravel
    ports:
      - "8000:80"
    restart: always
