version: "3"
services:
  laravel:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: cube_php_laravel_laravel
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    environment:
      - DD_SERVICE=cube_sample_app_php_laravel
      # send traces to CubeAPM
      - DD_TRACE_AGENT_URL=http://host.docker.internal:3130
      
      # optional settings
      # - DD_ENV=myenv
      # - DD_VERSION=1.2.3
      # - DD_TAGS=mykey1:myvalue1,mykey2:myvalue2

      # Print Datadog tracer startup logs on screen
      # - DD_TRACE_STARTUP_LOGS=true
      # Enable Datadog tracer debug logging if needed to see detailed logs
      # - DD_TRACE_DEBUG=true
    restart: always

  laravel_worker:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
    command: ["php", "artisan", "queue:work"]
    container_name: cube_php_laravel_laravel_worker
    depends_on:
      - mysql
    environment:
      - DD_SERVICE=cube_sample_app_php_laravel
      # send traces to CubeAPM
      - DD_TRACE_AGENT_URL=http://host.docker.internal:3130

      # optional settings
      # - DD_ENV=myenv
      # - DD_VERSION=1.2.3
      # - DD_TAGS=mykey1:myvalue1,mykey2:myvalue2

      # Print Datadog tracer startup logs on screen
      # - DD_TRACE_STARTUP_LOGS=true
      # Enable Datadog tracer debug logging if needed to see detailed logs
      # - DD_TRACE_DEBUG=true
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_php_laravel_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_php_laravel_mysql:/var/lib/mysql
    ports:
      - "3306:3306"


  redis:
    image: redis:alpine3.18
    container_name: cube_php_laravel_redis

volumes:
  cube_php_laravel_mysql:
