version: "3"
services:
  laravel:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        # send traces directly to CubeAPM
        # DD_TRACE_AGENT_URL: http://host.docker.internal:3130

        DD_AGENT_HOST: datadog-agent
        
        # OR send to Datadog Agent (Traces on 8126, Metrics on 8125)
        # DD_AGENT_HOST: host.docker.internal
        # DD_DOGSTATSD_URL: udp://host.docker.internal:8125
    container_name: cube_php_laravel_laravel
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    restart: always

  laravel_worker:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        # send traces directly to CubeAPM
        # DD_TRACE_AGENT_URL: http://host.docker.internal:3130

        DD_AGENT_HOST: datadog-agent
        
        # OR send to Datadog Agent (Traces on 8126, Metrics on 8125)
        # DD_AGENT_HOST: host.docker.internal
        # DD_DOGSTATSD_URL: udp://host.docker.internal:8125
    command: ["php", "artisan", "queue:work"]
    container_name: cube_php_laravel_laravel_worker
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_php_laravel_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_php_laravel_mysql:/var/lib/mysql
    ports:
      - "33066:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_php_laravel_redis

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: cube_php_laravel_datadog_agent
    environment:
      - DD_API_KEY=your_datadog_api_key_here
      # Send runtime metrics to CubeAPM
      - DD_DD_URL=http://host.docker.internal:3130
      # Send traces to CubeAPM
      - DD_APM_DD_URL=http://host.docker.internal:3130
      # Send logs to CubeAPM
      - DD_LOGS_CONFIG_LOGS_DD_URL=host.docker.internal:3130
      - DD_LOGS_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_LOGS_CONFIG_USE_HTTP=true
      - DD_LOGS_CONFIG_LOGS_NO_SSL=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      # Accept traces and metrics from applications
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - "8126:8126"
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  cube_php_laravel_mysql:
