version: "3"
services:
  laravel:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: cube_php_laravel_laravel
    environment:
      - OTEL_SERVICE_NAME=cube_sample_php_laravel_otel
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip 
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp

      # print traces on console
      - OTEL_LOG_LEVEL=debug
      # send traces to CubeAPM
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces 
      - OTEL_PHP_AUTOLOAD_ENABLED=true 
      - OTEL_PROPAGATORS=baggage,tracecontext 
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    restart: always

  laravel_worker:
    platform: linux/amd64
    build:
      context: .
      # dockerfile: Dockerfile
    command: ["php", "artisan", "queue:work"]
    container_name: cube_php_laravel_laravel_worker
    environment:
      - OTEL_SERVICE_NAME=cube_sample_php_laravel_otel
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip 
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp

      # print traces on console
      - OTEL_LOG_LEVEL=debug
      # send traces to CubeAPM
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces 
      - OTEL_PHP_AUTOLOAD_ENABLED=true 
      - OTEL_PROPAGATORS=baggage,tracecontext 
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_php_laravel_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_php_laravel_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

    
  redis:
    image: redis:alpine3.18
    container_name: cube_php_laravel_redis

volumes:
  cube_php_laravel_mysql:
