version: "3"
services:
  laravel:
    build:
      context: .
    container_name: cube_php_laravel
    environment:
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip
      - OTEL_PROPAGATORS=baggage,tracecontext
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

      - OTEL_SERVICE_NAME=cube_sample_php_laravel

      # print traces on console
      - OTEL_TRACES_EXPORTER=console
      # send traces to CubeAPM
      # - OTEL_TRACES_EXPORTER=otlp
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:8.0
    container_name: cube_php_laravel_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - cube_php_laravel_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine3.18
    container_name: cube_php_laravel_redis

volumes:
  cube_php_laravel_mysql: